"""Run every public benchmark, then write bench/results/BENCHMARKS.md and the README's
results block from the JSON files. Numbers are copied, never typed.

    make bench                                  # = uv run python bench/run.py
    uv run python bench/run.py --skip-voice     # reuse the last voice.json (it takes minutes)
    uv run python bench/run.py --tar PATH       # an existing LibriSpeech test-clean.tar.gz
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

BENCH = Path(__file__).resolve().parent
ROOT = BENCH.parent
RESULTS = BENCH / "results"
README = ROOT / "README.md"
START, END = "<!-- results:start -->", "<!-- results:end -->"
GITHUB = "https://github.com/RatnamOjha/saysafe/blob/main/"  # absolute: PyPI shows the README too


def run(script: str, *args: str) -> None:
    print(f"\n== {script} {' '.join(args)}", flush=True)
    subprocess.run([sys.executable, str(BENCH / script), *args], check=True, cwd=ROOT)


def load(name: str) -> dict | None:
    path = RESULTS / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


def frac(r: dict) -> str:
    if not r["n"]:
        return f"{r['count']} of 0"
    share = 100 * r["count"] / r["n"]
    shown = "0%" if share == 0 else f"{share:.3f}%" if share < 0.1 else f"{share:.1f}%"
    return f"{r['count']} of {r['n']} ({shown})"  # never round a real miss down to 0


def pct(r: dict) -> str:
    return f"{100 * r['rate']:.1f}%" if r["n"] else "n/a"


def benchmarks_md(latency: dict, voice: dict | None, privacy: dict) -> str:
    md = ["# Benchmarks", "",
          f"Generated by `make bench` on {latency['machine']}, Python {latency['python']}. "
          "Every number comes from the scripts in `bench/`; rerun them to check.", ""]  # fmt: skip

    p, a = latency["privacy_check"], latency["approval_start_and_reply"]
    md += ["## Speed", "",
           "| Check | p50 | p95 | p99 | calls |", "|---|---|---|---|---|",
           f"| `PrivacyGuard.check` ({p['replies']} replies, {p['mean_words']} words on average) "
           f"| {p['p50_ms']} ms | {p['p95_ms']} ms | {p['p99_ms']} ms | {p['n']} |",
           f"| `ApprovalGuard.start` + `reply` | {a['p50_ms']} ms | {a['p95_ms']} ms "
           f"| {a['p99_ms']} ms | {a['n']} |", ""]  # fmt: skip

    md += ["## Voice ID on LibriSpeech", ""]
    if voice is None:
        md += ["Not run yet: `uv run python bench/voice_librispeech.py`.", ""]
    else:
        md += [f"{voice['data']}. {voice['model']} on {voice['machine']}.", "",
               "Every cut of speech scored against every enrolled speaker, at the packaged "
               "thresholds:", "",
               "| Speech | Owner accepted | Stranger accepted | EER | No score | Score time (p50) |",
               "|---|---|---|---|---|---|"]  # fmt: skip
        for c in voice["per_cut"]:
            md.append(f"| {c['speech_s']} s | {frac(c['owner_accepted_at_packaged'])} | "
                      f"{frac(c['stranger_accepted_at_packaged'])} | {100 * c['eer']:.1f}% | "
                      f"{frac(c['no_score'])} | {c['score_ms_p50']} ms |")  # fmt: skip
        cal = voice["calibrated"]
        md += ["", f"End to end through `ApprovalGuard` ({voice['end_to_end_on']}). "
               f"Calibrated thresholds (accept {cal['t_accept']}, reject {cal['t_reject']}) come "
               f"from `saysafe.calibrate` on {voice['calibrated_on']}.", "",
               "| Thresholds, reply length | Owner approved by voice | Stranger approved |",
               "|---|---|---|"]  # fmt: skip
        for name, r in voice["end_to_end"].items():
            md.append(f"| {name} | {frac(r['owner_approved'])} | {frac(r['stranger_approved'])} |")
        md += ["", "An owner who isn't approved by voice isn't refused: the step goes to a phone "
               "tap. A stranger who is approved has passed the voice tier, which the default "
               "policy keeps for purchases under $75 and emails to known contacts.", "",
               "LibriSpeech is clean read speech, close to the best case. A wearable mic in a "
               "noisy room will do worse, and recordings or voice clones of the owner aren't "
               "tested here: calibrate on your own recordings, and read the threat model.", ""]  # fmt: skip

    md += ["## Private replies", ""]
    if privacy.get("status") != "ok":
        md += [f"Not measured yet: {privacy.get('reviewed', 0)} of {privacy.get('total', 0)} "
               "labels reviewed. The benchmark only counts replies a person has labelled.", ""]  # fmt: skip
    else:
        md += [f"{privacy['items']} reviewed replies ({privacy['dataset']}), rules only, text "
               "alone, others present.", "", "| Result | Value |", "|---|---|",
               f"| Sensitive replies spoken in full | {frac(privacy['sensitive_spoken_in_full_with_others'])} |",
               f"| Sensitive value left in a rewrite | {frac(privacy['sensitive_value_left_in_rewrite'])} |",
               f"| Public replies withheld | {frac(privacy['public_withheld_with_others'])} |",
               f"| Injected instructions that changed routing | {frac(privacy['injections_that_changed_routing'])} |",
               ""]  # fmt: skip
    return "\n".join(md)


def readme_block(latency: dict, voice: dict | None, privacy: dict) -> str:
    p = latency["privacy_check"]
    rows = [f"| Privacy check, per reply (p50 / p95) | {p['p50_ms']} / {p['p95_ms']} ms "
            f"on {latency['machine']} |"]  # fmt: skip
    if voice is not None:
        by_cut = {c["speech_s"]: c for c in voice["per_cut"]}
        e2e = voice["end_to_end"]
        rows += [
            f"| Voice ID equal error rate, 3 s / 0.5 s of speech | "
            f"{100 * by_cut[3.0]['eer']:.1f}% / {100 * by_cut[0.5]['eer']:.1f}% |",
            f"| Strangers approved by voice, end to end (packaged thresholds, 1 s reply) | "
            f"{frac(e2e['packaged, reply 1.0 s']['stranger_approved'])} |",
            f"| Owner approved without a phone tap (same) | "
            f"{frac(e2e['packaged, reply 1.0 s']['owner_approved'])} |",
        ]  # fmt: skip
    if privacy.get("status") == "ok":
        rows.append(f"| Sensitive replies spoken in full with others present | "
                    f"{frac(privacy['sensitive_spoken_in_full_with_others'])} |")  # fmt: skip
    else:
        rows.append(f"| Private-reply accuracy | not measured yet ({privacy.get('reviewed', 0)} "
                    f"of {privacy.get('total', 0)} labels reviewed) |")  # fmt: skip
    note = ("Voice numbers are on LibriSpeech (clean read speech), close to the best case. "
            if voice else "")  # fmt: skip
    return "\n".join([START, "", "| Result | Value |", "|---|---|", *rows, "",
                      f"{note}Details and caveats: [bench/results/BENCHMARKS.md]"
                      f"({GITHUB}bench/results/BENCHMARKS.md). Rerun with `make bench`.", "", END])  # fmt: skip


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-voice", action="store_true")
    ap.add_argument("--tar", help="an existing LibriSpeech test-clean.tar.gz")
    args = ap.parse_args()
    run("latency.py")
    run("privacy_replies.py")
    if not args.skip_voice:
        run("voice_librispeech.py", *(["--tar", args.tar] if args.tar else []))
    latency, voice, privacy = load("latency"), load("voice"), load("privacy")
    (RESULTS / "BENCHMARKS.md").write_text(benchmarks_md(latency, voice, privacy))
    text = README.read_text()
    block = readme_block(latency, voice, privacy)
    README.write_text(re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, text,
                             flags=re.S))  # fmt: skip
    print(f"\nWrote {RESULTS / 'BENCHMARKS.md'} and the README results block.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
